app/blueprints/dashboard/__init__.py
from flask import Blueprint

dashboard_bp = Blueprint('dashboard', __name__, url_prefix='/dashboard')

from . import routes

app/blueprints/dashboard/routes.py
from flask import Flask, render_template, redirect, url_for, request, session, flash, Blueprint, jsonify
import requests
import json
from . import dashboard_bp
from config import JSONBIN_CURSOS_URL, HEADERS_CURSOS, JSONBIN_USERS_URL, HEADERS_USERS, JSONBIN_RECETAS_URL
import cloudinary
import cloudinary.uploader
import cloudinary.api
import mysql.connector
import pymysql
from flask_mysqldb import MySQL
from app import mysql


cloudinary.config( 
    cloud_name = "dzjpeuzcn", 
    api_key = "859251897787294", 
    api_secret = "sxJLKRkscHL7ChM-xpbnSdpYUuc",
    secure=True
)

dashboard_bp = Blueprint('dashboard_bp', __name__)

def obtener_cursos_nuevos(limit=5):
    try:
        cursor = mysql.connection.cursor()
        query = "SELECT id, titulo, descripcion, precio, dificultad, fecha, foto FROM cursos ORDER BY id DESC LIMIT %s"
        cursor.execute(query, (limit,))
        cursos = cursor.fetchall()
        cursor.close()

        cursos_info = []
        for curso in cursos:
            curso_data = {
                'id': curso[0],
                'titulo': curso[1],
                'descripcion': curso[2],
                'precio': curso[3],
                'dificultad': curso[4],
                'fecha': curso[5],
                'foto': curso[6]
            }
            cursos_info.append(curso_data)
        return cursos_info
    except Exception as e:
        print(f"Error al obtener los cursos nuevos: {str(e)}")
        return []
    

def obtener_recetas_nuevas(limit=5):
    try:
        cursor = mysql.connection.cursor()
        query = "SELECT id, titulo_receta, descripcion, foto FROM recetas ORDER BY id DESC LIMIT %s"
        cursor.execute(query, (limit,))
        recetas = cursor.fetchall()
        cursor.close()

        recetas_info = []
        for receta in recetas:
            receta_data = {
                'id': receta[0],
                'titulo': receta[1],
                'descripcion': receta[2],
                'foto': receta[3],
            }
            recetas_info.append(receta_data)
        return recetas_info
    except Exception as e:
        print(f"Error al obtener las recetas nuevas: {str(e)}")
        return []

@dashboard_bp.route('/')
def home():
    nuevos_cursos = obtener_cursos_nuevos(limit=3)
    nuevas_recetas = obtener_recetas_nuevas(limit=3)
    return render_template('dashboard/index.html', nuevosCursos=nuevos_cursos, recetasNuevas=nuevas_recetas)


@dashboard_bp.route('/nosotros')
def nosotros():
    return render_template('dashboard/nosotros.html')

@dashboard_bp.route('/compras')
def compras():
    return render_template('dashboard/compras.html')

@dashboard_bp.route('/preguntas')
def preguntas():
    return render_template('dashboard/preguntasFrecuentes.html')

@dashboard_bp.route('/registro')
def registro():
    return render_template('auth/register.html')

@dashboard_bp.route('/login')
def login():
    return render_template('auth/login.html')


@dashboard_bp.route('/perfil')
def perfil():
    if 'userid' in session:
        user_id = session['userid']
        
        cursor = mysql.connection.cursor()

        try:
            cursor.execute("SELECT id, email, nombre, usuario, chef, bio, foto FROM usuarios WHERE id = %s", (user_id,))
            usuario_logueado = cursor.fetchone()
        except Exception as e:
            flash(f'Error al cargar el perfil: {str(e)}')
            usuario_logueado = None
        finally:
            cursor.close()

        if usuario_logueado:
            user_data = {
                'id': usuario_logueado[0],
                'email': usuario_logueado[1],
                'nombre': usuario_logueado[2],
                'usuario': usuario_logueado[3],
                'chef': usuario_logueado[4],
                'bio': usuario_logueado[5],
                'foto': usuario_logueado[6],
            }
            return render_template('dashboard/miPerfil.html', user=user_data)
    
    return redirect(url_for('auth.login'))


@dashboard_bp.route('/editarperfil', methods=['GET', 'POST'])
def editarperfil():
    if 'userid' not in session: 
        flash('Por favor, inicia sesión para editar tu perfil.')
        return redirect(url_for('auth.login'))

    user_id = session['userid']

    if request.method == 'POST':
        nombre = request.form['nombre']
        usuario = request.form['usuario']
        bio = request.form['bio']

        foto_url = None
        foto = request.files.get('foto')

        if foto:
            try:
                upload_result = cloudinary.uploader.upload(foto)
                foto_url = upload_result['url']
            except Exception as e:
                flash(f'Error al subir la foto: {str(e)}')
                return redirect(url_for('dashboard_bp.editarperfil'))

        cursor = mysql.connection.cursor()

        try:
            if foto_url: 
                cursor.execute("UPDATE usuarios SET nombre = %s, usuario = %s, bio = %s, foto = %s WHERE id = %s", (nombre, usuario, bio, foto_url, user_id))
            else:  
                cursor.execute("UPDATE usuarios SET nombre = %s, usuario = %s, bio = %s,  WHERE id = %s", (nombre, usuario, bio, user_id))
            mysql.connection.commit()
            flash('Perfil actualizado con éxito.')
        except Exception as e:
            mysql.connection.rollback()
            flash(f'Error al actualizar el perfil: {str(e)}')
        finally:
            cursor.close()

        return redirect(url_for('dashboard_bp.perfil'))

    cursor = mysql.connection.cursor()
    try:
        cursor.execute("SELECT id, email, nombre, usuario, bio, chef, foto FROM usuarios WHERE id = %s", (user_id,))
        usuario_logueado = cursor.fetchone()
    except Exception as e:
        flash(f'Error al cargar los datos del usuario: {str(e)}')
        usuario_logueado = None
    finally:
        cursor.close()

    if not usuario_logueado:
        flash('No se pudo cargar el perfil del usuario.')
        return redirect(url_for('auth.login'))

    user_data = {
        'id': usuario_logueado[0],
        'email': usuario_logueado[1],
        'nombre': usuario_logueado[2],
        'usuario': usuario_logueado[3],
        'bio': usuario_logueado[4],
        'chef': usuario_logueado[5],
        'foto': usuario_logueado[6],
    }

    return render_template('dashboard/editarPerfil.html', user=user_data)

@dashboard_bp.route('/recetas')
def recetas():
    cursor = mysql.connection.cursor()
    
    try:
        cursor.execute("SELECT id, titulo_receta, foto FROM recetas")
        recetas_info = cursor.fetchall()

        recetas_info = [{'id': receta[0], 'titulo_receta': receta[1], 'foto': receta[2]} for receta in recetas_info]
        
        print(f'Recetas cargadas: {recetas_info}')
        
        if not recetas_info:
            flash('No se encontraron recetas disponibles.', 'warning')
            print('No se encontraron recetas disponibles.')
            
    except Exception as e:
        flash(f'Error al cargar las recetas: {str(e)}', 'error')
        print(f'Error al cargar las recetas: {str(e)}') 
        recetas_info = []

    finally:
        cursor.close()

    print(f'Información de recetas a pasar al template: {recetas_info}')
    return render_template('dashboard/recetas.html', recetasInfo=recetas_info)


@dashboard_bp.route('/cursos')
def cursos():
    try:
        cursor = mysql.connection.cursor()
        cursor.execute("SELECT id, titulo, descripcion, precio, dificultad, fecha, foto FROM cursos") 
        cursos = cursor.fetchall()
        
        cursos_info = []
        for curso in cursos:
            curso_data = {
                'id': curso[0],
                'titulo': curso[1],
                'descripcion': curso[2],
                'precio': curso[3],
                'dificultad': curso[4],
                'fecha': curso[5],
                'foto': curso[6]
            }
            cursos_info.append(curso_data)
        cursor.close()

        return render_template('dashboard/cursos.html', cursosInfo=cursos_info)

    except Exception as e:
        flash(f'Error al obtener los cursos: {str(e)}')
        return render_template('dashboard/cursos.html', cursosInfo=[])


@dashboard_bp.route('/eliminarcurso', methods=['POST'])
def eliminarcurso():
    if 'userid' not in session:
        flash('Debes iniciar sesión para realizar esta acción.', 'error')
        return redirect(url_for('auth.login'))

    curso_id = request.form.get('curso_id')

    if not curso_id:
        flash('No se especificó el curso a eliminar.', 'error')
        return redirect(url_for('dashboard_bp.cursos'))

    cursor = mysql.connection.cursor()
    try:
        cursor.execute("SELECT id FROM cursos WHERE id = %s AND userid = %s", (curso_id, session['userid']))
        curso = cursor.fetchone()

        if curso:
            print(f"Curso encontrado: {curso}")
        else:
            print("Curso no encontrado o no pertenece al usuario.")
            flash('No tienes permiso para eliminar este curso o no existe.', 'error')
            return redirect(url_for('dashboard_bp.cursos'))

        cursor.execute("DELETE FROM cursos WHERE id = %s AND userid = %s", (curso_id, session['userid']))
        mysql.connection.commit()

        flash('Curso eliminado correctamente.', 'success')

    except Exception as e:
        mysql.connection.rollback()
        flash(f'Ocurrió un error al eliminar el curso: {str(e)}', 'error')
    finally:
        cursor.close()

    return redirect(url_for('dashboard_bp.cursos'))


@dashboard_bp.route('/eliminarreceta', methods=['POST', 'GET'])
def eliminarreceta():
    if 'userid' not in session:
        flash('Debes iniciar sesión para realizar esta acción.', 'error')
        return redirect(url_for('auth.login'))

    receta_id = request.form.get('receta_id')

    if not receta_id:
        flash('No se especificó la receta a eliminar.', 'error')
        return redirect(url_for('dashboard_bp.recetas'))

app/templates/dashboard/compras.html
{% extends "layout.html" %}

{% block title %} Compras {% endblock %}

{% block content %}

    <section >
        <h1 class="dialogo">Compras</h1>
    </section>
    <section class="sectionBlanco ">
        <div class="flex container">
            <div class="caja">
                <p>En RecipeRealm seleccionamos cuidadosamente los mejores ingredientes de nuestros supermercados aliados:</p>
            </div>
            <section class="flex container supermercados">
                <div>
                    <a href="https://www.jumbo.com" target="_blank">
                        <img src="/static/img/cartelMadera.png" alt="Jumbo" height="90px">
                    </a>
                    <p>Jumbo</p>
                </div>
                <div>
                    <a href="https://www.coto.com" target="_blank">
                        <img src="/static/img/cartelMadera.png" alt="Coto" height="90px">
                    </a>
                    <p>Coto</p>
                </div>
                <div>
                    <a href="https://www.carrefour.com" target="_blank">
                        <img src="/static/img/cartelMadera.png" alt="Carrefour" height="90px">
                    </a>
                    <p>Carrefour</p>
                </div>
            </section>
        </div>
    </section>

    <h1 class="container espacioAbajo">¿Cómo funciona la sección de compra?</h1>

    <section class="sectionBlanco ">
        <div class="flex container">
            <img src="/static/img/ingredientes.png" alt="Ingredientes" height="150px">
            <div class="caja">
                <h1>1. Seleccionar ingredientes</h1>
                <p>Al visualizar una receta, tenés la opción de marcar los ingredientes que no tenés en tu hogar. Estos se agregarán a una “lista de compras”
                </p>
            </div>
        </div>
    </section>

    <section class="sectionBlanco ">
        <div class="flex container">
            <div class="caja">
                <h1>2. Ver precios</h1>
                <p>Una vez seleccionados los ingredientes la plataforma te va a mostrar cuanto costarían estos ingredientes en cada uno de los supermercados disponibles.</p>
            </div>
            <img src="/static/img/precios.png" alt="Precios" height="180px">
        </div>
    </section>

    <section class="sectionBlanco ">
        <div class="flex container">
            <img src="/static/img/elegirSupermercado.png" alt="Supermercado" height="180px">
            <div class="caja">
                <h1>3. Elegir el supermercado</h1>
                <p>Despues de elegir el supermercado verás el precio de los productos y con un botón podrás ir al supermercado elegido.
                </p>
            </div>
        </div>
    </section>

    <section class="cuadroCompras container">
        <p class="pPequeño">Cada supermercado tiene su propia sección de compras con promociones y descuentos actualizados, por lo que te recomendamos revisar los precios antes de completar la compra.</p>
    </section>
 
    {% endblock %}

app/templates/dashboard/cursos.html
{% extends "layout.html" %}

{% block title %} Compras {% endblock %}

{% block content %}

<section>
    <div class="barraBusqueda">
        <input type="text" placeholder="Buscar...">
        <button><img src="{{ url_for('static', filename='img/search-icon.png') }}" alt="Buscar" width="20px"></button>
    </div>
</section>

<div class="container">
    <h1 class="espacioAbajo">Cursos</h1>
    <p>Elegí el nivel de dificultad</p>
    <div class="filtros">
        <div class="cursoNivel cursoPrincipiante">
            <span>Principiante</span>
            <img src="/static/img/espada.png" alt="espada">
        </div>
        <div class="cursoNivel cursoIntermedio">
            <span>Intermedio</span>
            <img src="/static/img/espada.png" alt="espada">
            <img src="/static/img/espada.png" alt="espadas">
        </div>
        <div class="cursoNivel cursoAvanzado">
            <span>Avanzado</span>
            <img src="/static/img/espada.png" alt="espada">
            <img src="/static/img/espada.png" alt="espadas">
            <img src="/static/img/espada.png" alt="espadas">
        </div>
    </div>
</div>


<section class="cursosNuevos container">
    <h2>Cursos Nuevos</h2>
    {% for curso in cursosInfo %}
    <div class="cursoTarjet">
        <a href="{{ url_for('dashboard_bp.get_curso_by_id', curso_id=curso.id) }}">
            <img src="{{ curso['foto'] }}" alt="Curso imagen">
        </a>
        <h3>{{ curso['titulo'] }}</h3>
        <p>${{ curso['precio'] }}</p>
        <p>{{ curso['fecha'] }}</p>
        <p>{{ curso['dificultad'] }}</p>
    </div>
    {% endfor %}
</section>

    {% endblock %}

app/templates/dashboard/editarCurso.html
{% extends "layout.html" %}

{% block title %} Subir curso {% endblock %}

{% block content %}

<section class="">
    <div class="dialogo">
        <h1>Editar curso</h1>
    </div>
        <form class="containerRegistro flex" action="{{ url_for('dashboard_bp.editarcurso', curso_id=curso.id) }}" method="POST" enctype="multipart/form-data">
            <div class="formDerechaRegistro" >
            <div class="formRegistro">
                <label for="tituloCurso">Titulo</label>
                <input type="text" id="tituloCurso" name="titulo_curso" value="{{ curso.titulo }}">
            </div>
    
            <div class="formRegistro flex">
                <div>
                    <label for="lugar">Lugar/Sitio web</label>
                    <input type="text" id="lugar" name="lugar" value="{{ curso.lugar }}">
                </div>
                <div>
                    <label for="cupos">Cupos disponibles</label>
                    <input type="text" id="cupos" name="cupos" value="{{ curso.cupos_disponibles }}">
                </div>
                <div>
                    <label for="precio">Precio</label>
                    <input type="text" id="precio" name="precio" value="{{ curso.precio }}">
                </div>
            </div>

            <div class="formRegistro">
                <label for="fecha">Fecha del curso</label>
                <input type="date" id="fecha" name="fecha" value="{{ curso.fecha }}">
            </div>
            <div>
                <label for="hora">Hora del curso</label>
                <input type="time" id="hora" name="hora">
            </div>
            <div>
                <label for="dificultad">Dificultad</label>
                <div>
                    <div class="filtros">
                        <!-- Principiante -->
                        <input type="radio" class="cursoPrincipiante" id="principiante" name="dificultad" value="Principiante" hidden required>
                        <div class="dificultad cursoPrincipiante" onclick="document.getElementById('principiante').checked = true;">
                            <div>
                                <span>Principiante</span>
                            </div>
                            <div>
                                <img src="/static/img/espada.png" alt="espada">
                            </div>
                        </div>
                    
                        <!-- Intermedio -->
                        <input type="radio" class="cursoIntermedio" id="intermedio" name="dificultad" value="Intermedio" hidden required>
                        <div class="dificultad cursoIntermedio" onclick="document.getElementById('intermedio').checked = true;">
                            <div>
                                <span>Intermedio</span>
                            </div>
                            <div>
                                <img src="/static/img/espada.png" alt="espada">
                                <img src="/static/img/espada.png" alt="espada">
                            </div>
                        </div>
                    
                        <!-- Avanzado -->
                        <input type="radio" class="cursoAvanzado" id="avanzado" name="dificultad" value="Avanzado" hidden required>
                        <div class="dificultad cursoAvanzado" onclick="document.getElementById('avanzado').checked = true;">
                            <div>
                                <span>Avanzado</span>
                            </div>
                            <div>
                                <img src="/static/img/espada.png" alt="espada">
                                <img src="/static/img/espada.png" alt="espada">
                                <img src="/static/img/espada.png" alt="espada">
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="formRegistro">
                <label for="foto">Foto ilustrativa</label>
                <input type="file" id="foto" name="foto" accept="image/*">
            </div>
            </div>
            

            
    
            <div  class="formDerechaRegistro">
                <div>
                    <label for="desCurso">Descripcion</label>
                    <textarea id="desCurso" name="desCurso" placeholder="1- poner el agua a hervir" class="textareaRegistro">{{ curso.descripcion }}</textarea>
                </div>

        
                <button type="submit" class="btnRojo">Subir curso</button>
            </div>
        </form>
</section>

{% endblock %}

app/templates/dashboard/editarPerfil.html
{% extends "layout.html" %} {% block title %} Editar Perfil {% endblock %} {%
block content %}
<section>
  <div class="">
    <div class="dialogo">
      <h1>Editar perfil</h1>
    </div>
    <form
      method="POST"
      class="containerRegistro flex"
      enctype="multipart/form-data"
    >
      <div class="formRegistro">
        <div class="formRegistro">
          <label for="nombre">Nombre:</label>
          <input
            type="text"
            id="nombre"
            name="nombre"
            value="{{ user.nombre }}"
            required
          />
        </div>
        <div class="formRegistro">
          <label for="usuario">Usuario:</label>
          <input
            type="text"
            id="usuario"
            name="usuario"
            value="{{ user.usuario }}"
            required
          />
        </div>
        <div class="formRegistro">
          <label for="foto">Foto de perfil:</label>
          <input type="file" id="foto" name="foto" accept="image/*" />
        </div>
      </div>
      <div class="formDerechaRegistro">
        <label for="bio">Descripción:</label>
        <textarea id="bio" name="bio" required>{{ user.bio }}</textarea>
        <br />
        <button type="submit" class="btnRojo">Actualizar</button>
      </div>
    </form>
  </div>
</section>
{% endblock %}

app/templates/dashboard/editarReceta.html
{% extends "layout.html" %} {% block title %} Editar receta {% endblock %} {%
block content %}
<section class="">
  <div class="dialogo">
    <h1>Editar receta</h1>
  </div>

  {% with messages = get_flashed_messages(with_categories=true) %} {% if
  messages %}
  <div class="alert-container">
    {% for category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger">{{ message }}</div>
    {% elif category == 'success' %}
    <div class="alert alert-success">{{ message }}</div>
    {% endif %} {% endfor %}
  </div>
  {% endif %} {% endwith %}

  <form
    class="containerRegistro flex"
    action="{{ url_for('dashboard_bp.editarreceta', receta_id=receta.id) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="formDerechaRegistro">
      <div class="formRegistro">
        <label for="tituloReceta">Título</label>
        <input
          type="text"
          id="tituloReceta"
          name="titulo_receta"
          value="{{ receta.titulo_receta }}"
        />
      </div>

      <div class="formRegistro flex">
        <div>
          <label for="ingrediente">Ingrediente</label>
          <input
            type="text"
            id="ingrediente"
            name="ingrediente"
            placeholder="Pasta"
          />
        </div>
        <div>
          <label for="cantidad">Cantidad</label>
          <input
            type="text"
            id="cantidad"
            name="cantidad"
            placeholder="300gr"
          />
        </div>
        <div>
          <button id="agregarIngrediente" class="btnAmarillo">
            <img src="/static/img/upIngredientes.png" alt="" />
          </button>
        </div>
      </div>

      <div class="formRegistro">
        <textarea
          id="listaIngredientes"
          name="lista_ingredientes"
          placeholder="Sus ingredientes aparecerán aquí"
          readonly
        >
{{ receta.lista_ingredientes }}</textarea
        >
      </div>

      <div class="formRegistro flex">
        <div>
          <label for="categorias">Categorías</label>
          <select id="categorias" name="lista_categorias" class="custom-select">
            <option value="" disabled selected>Selecciona una categoría</option>
            <option value="italia">Italia</option>
            <option value="china">China</option>
            <option value="mexico">México</option>
            <option value="argentina">Argentina</option>
            <option value="brasil">Brasil</option>
            <option value="colombia">Colombia</option>
            <option value="dulces">Dulces</option>
            <option value="japon">Japón</option>
            <option value="españa">España</option>
            <option value="bebidas">Bebidas</option>
          </select>
        </div>
        <div>
          <button id="agregarCategoria" class="btnAmarillo">
            <img src="/static/img/upIngredientes.png" alt="" />
          </button>
        </div>
      </div>

      <div class="formRegistro">
        <textarea
          id="listaCategorias"
          name="lista_categorias"
          placeholder="Sus categorías aparecerán aquí"
          readonly
        >
{{ receta.lista_categorias }}</textarea
        >
      </div>
    </div>

    <div class="formDerechaRegistro">
      <div>
        <label for="descripcion">Descripción</label>
        <textarea
          id="descripcion"
          name="descripcion"
          placeholder="Escribe la preparación paso a paso"
          class="textareaRegistro"
        >
{{ receta.descripcion }}</textarea
        >
      </div>

      <div class="formRegistro">
        <label for="foto">Foto de la receta</label>
        <input type="file" id="foto" name="foto" accept="image/*" required />
      </div>

      <button type="submit" class="btnRojo">Actualizar receta</button>
    </div>
  </form>
</section>

{% endblock %}

app/templates/dashboard/miPerfil.html
{% extends "layout.html" %} {% block title %} Nosotros {% endblock %} {% block
content %}

<section>
  <div class="container">
    <div class="perfil">
      <img src="{{ user.foto }}" alt="Foto de perfil" class="perfil-img" />
      <div class="perfilInfo">
        <h2>{{user.usuario}}</h2>
        <p class="perfilTitulo">{{user.chef}}</p>
      </div>
    </div>
    <div class="sobreMi">
      <p>Sobre mí</p>
    </div>
  </div>

  <div class="containerRegistro">
    <div class="containerDatosPerfil">
      <p><strong>Nombre:</strong>{{user.nombre}}</p>
      <p><strong>Descripción:</strong></p>
      <p>{{user.bio}}</p>
    </div>
    <div class="containerBotones">
      <a href="{{ url_for('dashboard_bp.editarperfil') }}">
        <button class="btnRojo">Editar Perfil</button></a
      >
      <a href="{{ url_for('auth.logout') }}">
        <button class="btnRojo">Cerrar Sesión</button></a
      >

      <form
        action="{{ url_for('auth.eliminarperfil') }}"
        method="POST"
        style="display: inline"
        onsubmit="return confirm('¿Estás seguro de que deseas eliminar tu perfil? Esta acción no se puede deshacer.');"
      >
        <button type="submit" class="btnRojo">Eliminar perfil</button>
      </form>
    </div>
  </div>
</section>

{% endblock %}

app/templates/dashboard/misRecetas.html
{% extends "layout.html" %} {% block title %} Nosotros {% endblock %} {% block
content %}

<section>
  <div class="barraBusqueda">
    <input type="text" placeholder="Buscar..." />
    <button>
      <img
        src="{{ url_for('static', filename='img/search-icon.png') }}"
        alt="Buscar"
        width="20px"
      />
    </button>
  </div>
</section>

<section class="espacioAbajo">
  <h1 class="container espacioAbajo">Mis Recetas</h1>
</section>

<section class="cursosNuevos container">
  {% for receta in recetasInfo %}
  <div class="recetaTarjet">
    <a
      href="{{ url_for('dashboard_bp.get_receta_by_id', receta_id=receta.id) }}"
    >
      <img src="{{ receta.foto }}" alt="Receta" />
    </a>
    <h3>{{ receta.titulo_receta }}</h3>
    <div class="caja-botones">
      <a
        href="{{ url_for('dashboard_bp.editarreceta', receta_id=receta['id']) }}"
        class="btnRojo btnMisCursos"
        >Editar</a
      >
      <form
        action="{{ url_for('dashboard_bp.eliminarreceta') }}"
        method="POST"
        style="display: inline"
        onsubmit="return confirm('¿Estás seguro de que deseas eliminar la receta? Esta acción no se puede deshacer.');"
      >
        <input type="hidden" name="receta_id" value="{{ receta.id }}" />
        <button type="submit" class="btnRojo">Eliminar receta</button>
      </form>
    </div>
  </div>
  {% endfor %}
</section>

{% endblock %}

app/templates/dashboard/nosotros.html
{% extends "layout.html" %}

{% block title %} Nosotros {% endblock %}

{% block content %}

    <section >
        <h1 class="dialogo">RecipeRealm</h1>
    </section>

    <section class="sectionBlanco ">
        <div class="flex container">
            <img src="/static/img/descubri.png" alt="Descubri" height="150px">
            <div class="caja">
                <h1>Descubrí recetas</h1>
                <p>Explorá una gran variedad de recetas deliciosas para cada ocasión. Desde platillos sencillos hasta creaciones gourmet, te ayudamos a encontrar lo que mejor se adapte a tu gusto.</p>
            </div>
        </div>
    </section>

    <section class="sectionBlanco ">
        <div class="flex container">
            <div class="caja">
                <h1>Compartí Recetas</h1>
                <p>¡Tu cocina es única! Compartí tus mejores recetas con la comunidad y dejá que otros descubran tus platillos favoritos.</p>
            </div>
            <img src="/static/img/comparti.png" alt="Comparti" height="150px">
        </div>
    </section>

    <section class="sectionBlanco ">
        <div class="flex container">
            <img src="/static/img/guarda.png" alt="Guarda" height="150px">
            <div class="caja">
                <h1>Guardá recetas</h1>
                <p>Encontraste una receta que te encantó? Guardala en tu colección personal para tenerla siempre a mano y prepararla cuando quieras.
                </p>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <img src="/static/img/carpinchoConGorrito.png" alt="">
            {% if 'email' not in session %}
            <div class="botones container btnNosotros">
                <a href="{{ url_for('dashboard_bp.registro') }}" class="registro btn btnVerdeNosotros">Registro</a>
            </div>
            <div class="botones container btnNosotros">
                <a href="{{ url_for('dashboard_bp.login') }}" class="btnRojo btn">Iniciar sesión</a>
            </div>
            {% endif %}
        </div>
    </section>

    {% endblock %}