app/blueprints/dashboard/routes.py
from flask import Flask, render_template, redirect, url_for, request, session, flash, Blueprint, jsonify
import requests
import json
from . import dashboard_bp
from config import JSONBIN_CURSOS_URL, HEADERS_CURSOS, JSONBIN_USERS_URL, HEADERS_USERS, JSONBIN_RECETAS_URL
import cloudinary
import cloudinary.uploader
import cloudinary.api
import mysql.connector
import pymysql
from flask_mysqldb import MySQL
from app import mysql


cloudinary.config( 
    cloud_name = "dzjpeuzcn", 
    api_key = "859251897787294", 
    api_secret = "sxJLKRkscHL7ChM-xpbnSdpYUuc",
    secure=True
)

dashboard_bp = Blueprint('dashboard_bp', __name__)

def obtener_cursos_nuevos(limit=5):
    try:
        cursor = mysql.connection.cursor()
        query = "SELECT id, titulo, descripcion, precio, dificultad, fecha, foto FROM cursos ORDER BY id DESC LIMIT %s"
        cursor.execute(query, (limit,))
        cursos = cursor.fetchall()
        cursor.close()

        cursos_info = []
        for curso in cursos:
            curso_data = {
                'id': curso[0],
                'titulo': curso[1],
                'descripcion': curso[2],
                'precio': curso[3],
                'dificultad': curso[4],
                'fecha': curso[5],
                'foto': curso[6]
            }
            cursos_info.append(curso_data)
        return cursos_info
    except Exception as e:
        print(f"Error al obtener los cursos nuevos: {str(e)}")
        return []
    

def obtener_recetas_nuevas(limit=5):
    try:
        cursor = mysql.connection.cursor()
        query = "SELECT id, titulo_receta, descripcion, foto FROM recetas ORDER BY id DESC LIMIT %s"
        cursor.execute(query, (limit,))
        recetas = cursor.fetchall()
        cursor.close()

        recetas_info = []
        for receta in recetas:
            receta_data = {
                'id': receta[0],
                'titulo': receta[1],
                'descripcion': receta[2],
                'foto': receta[3],
            }
            recetas_info.append(receta_data)
        return recetas_info
    except Exception as e:
        print(f"Error al obtener las recetas nuevas: {str(e)}")
        return []

@dashboard_bp.route('/')
def home():
    nuevos_cursos = obtener_cursos_nuevos(limit=3)
    nuevas_recetas = obtener_recetas_nuevas(limit=3)
    return render_template('dashboard/index.html', nuevosCursos=nuevos_cursos, recetasNuevas=nuevas_recetas)


@dashboard_bp.route('/nosotros')
def nosotros():
    return render_template('dashboard/nosotros.html')

@dashboard_bp.route('/compras')
def compras():
    return render_template('dashboard/compras.html')

@dashboard_bp.route('/preguntas')
def preguntas():
    return render_template('dashboard/preguntasFrecuentes.html')

@dashboard_bp.route('/registro')
def registro():
    return render_template('auth/register.html')

@dashboard_bp.route('/login')
def login():
    return render_template('auth/login.html')


@dashboard_bp.route('/perfil')
def perfil():
    if 'userid' in session:
        user_id = session['userid']
        
        cursor = mysql.connection.cursor()

        try:
            cursor.execute("SELECT id, email, nombre, usuario, chef, bio, foto FROM usuarios WHERE id = %s", (user_id,))
            usuario_logueado = cursor.fetchone()
        except Exception as e:
            flash(f'Error al cargar el perfil: {str(e)}')
            usuario_logueado = None
        finally:
            cursor.close()

        if usuario_logueado:
            user_data = {
                'id': usuario_logueado[0],
                'email': usuario_logueado[1],
                'nombre': usuario_logueado[2],
                'usuario': usuario_logueado[3],
                'chef': usuario_logueado[4],
                'bio': usuario_logueado[5],
                'foto': usuario_logueado[6],
            }
            return render_template('dashboard/miPerfil.html', user=user_data)
    
    return redirect(url_for('auth.login'))


@dashboard_bp.route('/editarperfil', methods=['GET', 'POST'])
def editarperfil():
    if 'userid' not in session: 
        flash('Por favor, inicia sesión para editar tu perfil.')
        return redirect(url_for('auth.login'))

    user_id = session['userid']

    if request.method == 'POST':
        nombre = request.form['nombre']
        usuario = request.form['usuario']
        bio = request.form['bio']

        foto_url = None
        foto = request.files.get('foto')

        if foto:
            try:
                upload_result = cloudinary.uploader.upload(foto)
                foto_url = upload_result['url']
            except Exception as e:
                flash(f'Error al subir la foto: {str(e)}')
                return redirect(url_for('dashboard_bp.editarperfil'))

        cursor = mysql.connection.cursor()

        try:
            if foto_url: 
                cursor.execute("UPDATE usuarios SET nombre = %s, usuario = %s, bio = %s, foto = %s WHERE id = %s", (nombre, usuario, bio, foto_url, user_id))
            else:  
                cursor.execute("UPDATE usuarios SET nombre = %s, usuario = %s, bio = %s,  WHERE id = %s", (nombre, usuario, bio, user_id))
            mysql.connection.commit()
            flash('Perfil actualizado con éxito.')
        except Exception as e:
            mysql.connection.rollback()
            flash(f'Error al actualizar el perfil: {str(e)}')
        finally:
            cursor.close()

        return redirect(url_for('dashboard_bp.perfil'))

    cursor = mysql.connection.cursor()
    try:
        cursor.execute("SELECT id, email, nombre, usuario, bio, chef, foto FROM usuarios WHERE id = %s", (user_id,))
        usuario_logueado = cursor.fetchone()
    except Exception as e:
        flash(f'Error al cargar los datos del usuario: {str(e)}')
        usuario_logueado = None
    finally:
        cursor.close()

    if not usuario_logueado:
        flash('No se pudo cargar el perfil del usuario.')
        return redirect(url_for('auth.login'))

    user_data = {
        'id': usuario_logueado[0],
        'email': usuario_logueado[1],
        'nombre': usuario_logueado[2],
        'usuario': usuario_logueado[3],
        'bio': usuario_logueado[4],
        'chef': usuario_logueado[5],
        'foto': usuario_logueado[6],
    }

    return render_template('dashboard/editarPerfil.html', user=user_data)

@dashboard_bp.route('/recetas')
def recetas():
    cursor = mysql.connection.cursor()
    
    try:
        cursor.execute("SELECT id, titulo_receta, foto FROM recetas")
        recetas_info = cursor.fetchall()

        recetas_info = [{'id': receta[0], 'titulo_receta': receta[1], 'foto': receta[2]} for receta in recetas_info]
        
        print(f'Recetas cargadas: {recetas_info}')
        
        if not recetas_info:
            flash('No se encontraron recetas disponibles.', 'warning')
            print('No se encontraron recetas disponibles.')
            
    except Exception as e:
        flash(f'Error al cargar las recetas: {str(e)}', 'error')
        print(f'Error al cargar las recetas: {str(e)}') 
        recetas_info = []

    finally:
        cursor.close()

    print(f'Información de recetas a pasar al template: {recetas_info}')
    return render_template('dashboard/recetas.html', recetasInfo=recetas_info)


@dashboard_bp.route('/cursos')
def cursos():
    try:
        cursor = mysql.connection.cursor()
        cursor.execute("SELECT id, titulo, descripcion, precio, dificultad, fecha, foto FROM cursos") 
        cursos = cursor.fetchall()
        
        cursos_info = []
        for curso in cursos:
            curso_data = {
                'id': curso[0],
                'titulo': curso[1],
                'descripcion': curso[2],
                'precio': curso[3],
                'dificultad': curso[4],
                'fecha': curso[5],
                'foto': curso[6]
            }
            cursos_info.append(curso_data)
        cursor.close()

        return render_template('dashboard/cursos.html', cursosInfo=cursos_info)

    except Exception as e:
        flash(f'Error al obtener los cursos: {str(e)}')
        return render_template('dashboard/cursos.html', cursosInfo=[])


@dashboard_bp.route('/eliminarcurso', methods=['POST'])
def eliminarcurso():
    if 'userid' not in session:
        flash('Debes iniciar sesión para realizar esta acción.', 'error')
        return redirect(url_for('auth.login'))

    curso_id = request.form.get('curso_id')

    if not curso_id:
        flash('No se especificó el curso a eliminar.', 'error')
        return redirect(url_for('dashboard_bp.cursos'))

    cursor = mysql.connection.cursor()
    try:
        cursor.execute("SELECT id FROM cursos WHERE id = %s AND userid = %s", (curso_id, session['userid']))
        curso = cursor.fetchone()

        if curso:
            print(f"Curso encontrado: {curso}")
        else:
            print("Curso no encontrado o no pertenece al usuario.")
            flash('No tienes permiso para eliminar este curso o no existe.', 'error')
            return redirect(url_for('dashboard_bp.cursos'))

        cursor.execute("DELETE FROM cursos WHERE id = %s AND userid = %s", (curso_id, session['userid']))
        mysql.connection.commit()

        flash('Curso eliminado correctamente.', 'success')

    except Exception as e:
        mysql.connection.rollback()
        flash(f'Ocurrió un error al eliminar el curso: {str(e)}', 'error')
    finally:
        cursor.close()

    return redirect(url_for('dashboard_bp.cursos'))


@dashboard_bp.route('/eliminarreceta', methods=['POST', 'GET'])
def eliminarreceta():
    if 'userid' not in session:
        flash('Debes iniciar sesión para realizar esta acción.', 'error')
        return redirect(url_for('auth.login'))

    receta_id = request.form.get('receta_id')

    if not receta_id:
        flash('No se especificó la receta a eliminar.', 'error')
        return redirect(url_for('dashboard_bp.recetas'))

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Nova+Square&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&family=K2D:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Nova+Mono&family=Nova+Square&display=swap"
      rel="stylesheet"
    />
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar">
        <ul class="navLinks">
            <li><a href="{{ url_for('dashboard_bp.compras') }}">Compras</a></li>
            <li><a href="{{ url_for('dashboard_bp.nosotros') }}">Nosotros</a></li>
            <li><a href="{{ url_for('dashboard_bp.preguntas') }}">Preguntas frecuentes</a></li>
        </ul>
        <div class="logo">
            <a href="{{ url_for('dashboard_bp.home') }}">
                <img src="/static/img/Logo.png" alt="Logo">
            </a>
        </div>
        <div class="botones"> 
            {% if 'email' in session %}
                <div class="desplegable">
                    <button class="btn btnUser usuario" onclick="alternarDesplegable()">Usuario</button>
                    <div id="menuUsuario" class="contenidoDesplegable">
                        <a href="{{ url_for('dashboard_bp.perfil') }}">Mi perfil</a>
                        <a href="{{ url_for('dashboard_bp.recetas') }}">Recetas</a>
                        <a href="{{ url_for('dashboard_bp.subirreceta') }}">Subir receta</a>
                        <a href="{{ url_for('dashboard_bp.misrecetas') }}">Mis recetas</a>
                        <a href="{{ url_for('dashboard_bp.cursos') }}">Cursos</a>
                        {% if session.get('chef') == 'Chef' %}
                            <a href="{{ url_for('dashboard_bp.subircurso') }}">Subir curso</a>
                            <a href="{{ url_for('dashboard_bp.miscursos') }}">Mis cursos</a>
                        {% endif %}
                        <a href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
                    </div>
                </div>
            {% else %}
                <a href="{{ url_for('dashboard_bp.login') }}" class="btn iniciarSesion">Iniciar sesión</a>
                <a href="{{ url_for('dashboard_bp.registro') }}" class="btn registro">Registro</a>
            {% endif %}
        </div>  
    </nav>

    <div class="content">{% block content %} {% endblock %}</div>

    <div class="arbustos">
      <img src="/static/img/arbustos.png" alt="Arbustos" />
    </div>
    <footer>
      <div class="contenido footerBlanco">
        <div>
          <img src="/static/img/Logo.png" alt="Logo" class="logoFooter" />
        </div>
        <div class="footer-info">
          <div class="redes">
            <img src="/static/img/ubi.png" alt="direccion" />
            <p>
              123 Av. Calle en Buenos Aires, Buenos Aires Charlottesville, CA,
              12345
            </p>
          </div>
          <div class="redes">
            <img src="/static/img/telefono.png" alt="direccion" />
            <p>+54 9 01123213</p>
          </div>
          <div class="redes">
            <p>Redes Sociales:</p>
            <a href="#"><img src="/static/img/facebook.png" alt="" /></a>
            <a href="#"><img src="/static/img/twitter.png" alt="" /></a>
            <a href="#"><img src="/static/img/youtube.png" alt="" /></a>
            <a href="#"><img src="/static/img/instagram.png" alt="" /></a>
          </div>
        </div>
      </div>
      <div class="footer-nav">
        <a href="#">Sobre Nosotros</a>
        <a href="#">Contáctanos</a>
        <a href="#">Ayuda</a>
        <a href="#">Políticas de Privacidad</a>
        <a href="#">Avisos</a>
      </div>
      <div>
        <p class="copy">
          Copyright © 2024 - Delfino Constanza - Leonardelli Sofia - Sosa
          Nazarena
        </p>
      </div>
    </footer>

    <script src="{{ url_for('static', filename='js/js.js') }}"></script>
  </body>
</html>

app/templates/protected.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página Protegida</title>
</head>
<body>
    <h1>Bienvenido, {{ email }}!</h1>
    <p>Te logueaste</p>
    <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
</body>
</html>